[package]
name = "ku"
version = "0.0.1"
authors = [ "Martin Mašić" ]
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
rand = "0.9.1"
rand_chacha = "0.9"
colored = "3.0.0"
crossbeam = "0.8.4"
